# Metadata
title:          Rafaell Lycan
description:    >
                This is my localhost, where I (randomly) write about programming, the web, life and/or photography.
keywords:       >
                desenvolvedor, front end, back end, developer, php, javascript, node, laravel, angular, react, software
logo:           /assets/icons/favicon-192x192.png
image:          /assets/images/me.jpg
url:            https://rafaell-lycan.com
repository:     rafaell-lycan/rafaell-lycan.com
rss:            https://feeds.feedburner.com/rafaell-lycan
lang:           pt_BR

# Author Informations
author:
  name:         Rafaell Lycan
  first_name:   Rafaell
  last_name:    Lycan
  email:        sonny.webdsg@gmail
  location:     barcelona
  twitter:      rafaelllycan
  github:       rafaell-lycan
  gravatar:     dd1c977c7a3e384a9cdae3b5ddd9b006

# Config
conf:
  g_analytics:  UA-16383035-5
  g_verify:     k0stkb4kdmJ6rf6o_WvHllT9IC4NGb6CpZC8BUvsUrA
  disqus_name:  rafaelllycan
  theme_color:  "#5fbffd"
  hotjar_id:    617230

webmaster_verifications:
  google: k0stkb4kdmJ6rf6o_WvHllT9IC4NGb6CpZC8BUvsUrA

navigation:
  - text: Home
    url: /
    active: false
  - text: Articles
    url: /articles
    active: articles
  - text: About
    url: /about
    active: about


social:
  name:         Rafaell Lycan
  links:
    - https://twitter.com/RafaellLycan
    - https://www.facebook.com/rafaell.lycan
    - https://github.com/rafaell-lycan
    - http://instagram.com/rafaelllycan
    - https://www.linkedin.com/in/rafaelllycan/
    - https://keybase.io/rafaell
    - https://plus.google.com/+RafaellLycan

twitter:
  username:     RafaellLycan

facebook:
  app_id:       1160764874037367
  pixel_id:     1881654748526380

# Collections
collections:
  trips:
    output: false
    permalink: /trips/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "trips"
    values:
      layout: trip

# Paths
baseurl: ""
asset_path:     "assets"

# Conversion
markdown:       kramdown
highlighter:    rouge
kramdown:
  input:        GFM
  syntax_highlighter: rouge
  parse_block_html: true

sass:
  sass_dir:     _sass
  style:        :compressed

# Output
permalink:      /:year/:title/
paginate:       10
paginate_path:  "/articles/page/:num/"
future:         false
show_drafts:    false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-pagination
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jemoji

# Reading
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _scripts
  - package.json
  - gulpfile.js
  - webpack.config.js
  - README.md

compress_html:
  clippings: all
  comments: ["<!--[if ", "<![endif]-->"]
  endings: all
  startings: [body]
  profile: false
  blanklines: false